server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
  instance:
    prefer-ip-address: true #以ip注册到注册中心
spring:
  application:
    name: spring-cloud-config-server #服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mc023/aigou-config.git
          username: mc023
          password: zsmm123456